project_name: 'experiment2'
project_desc: 'ex2_vit_intra'
# learning-opt
device_num : [0]
device : 'cuda'
disable_logger: false
logger_id : null # 'fe88bxkx' # null
trained_model_name : null #'2024-08-30T13-31-49' # null
seed_number : 1234
batch_size : 32 # 4
num_workers : 16 # 16
max_epochs : 10
scheduler_eta_max: 0.00001  # 0.0001
scheduler_t_up: 1
scheduler_step_size: 10
scheduler_gamma: 1.0
lr: 0.00001
weight_decay: 0.00001
accumulate_grad_batches: 1
phase : 'train'

# model
obj_encoder_path : 'facebook/dinov2-base'
img_encoder_path : 'facebook/dinov2-base'
feature_dim : 768
# data
root_dir : './datasets/fathomnet-2025/'
centroid_path : './results/centroid_embs_256.pkl'
categories_path : './results/dist_categories.csv'
nclass : 79
kfold : true
kfold_nsplits : 10
obj_encoder_size : [256, 256]
img_encoder_size : [256, 256]
object_crop : 'narrow' # 'narrow', 'padding', 'square'
# model
intra_env_attn : true
inter_env_attn : false
#backbone_training : true
#region_pooling_attn: true
#decoder: true
#cnn_extractor : true
#cnn_texture_input : true
#cnn_rgb_input : false
# loss
#ce_lambda : 1.0
#ce_aux_lambda: 0.0
lambda_bio : 0.0